baseURL = "https://zhiqiang21.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"


theme = "LeaveIt"


[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
